name: webview
description: "Convert website to App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  pull_to_refresh: ^2.0.0
  flutter_inappwebview: ^6.1.0+1
  url_launcher: ^6.3.0
  app_settings: ^5.1.1
  permission_handler: ^11.3.1
  open_settings_plus: ^0.3.3
  fluttertoast: ^8.2.8
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
